services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack
    restart: on-failure:2
    ports:
      # DSM Docker에서 WebStation 접근용 포트 (호스트 포트에 바인딩)
      - "52045:80"  # BookStack 웹 인터페이스
    environment:
      - TZ=Asia/Seoul
      # DSM Docker에서는 PUID/PGID 설정 제거 (볼륨 권한 문제 해결)
      # - PUID=1026
      # - PGID=100
      # 필수: 애플리케이션 URL 설정 (WebStation에서 접근할 수 있는 주소)
      - APP_URL=http://localhost:52045
      # 데이터베이스 설정 (MariaDB 사용 - 더 안정적)
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=JSlee.9500266
      - DB_DATABASE=bookstackapp
      # SQLite 사용 시 아래 주석 해제
      # - DB_CONNECTION=sqlite
      # - DB_DATABASE=/config/bookstack.db
      # 선택: 메일 설정 (비밀번호 재설정용)
      # - MAIL_DRIVER=smtp
      # - MAIL_HOST=smtp.gmail.com
      # - MAIL_PORT=587
      # - MAIL_USERNAME=your_email@gmail.com
      # - MAIL_PASSWORD=your_password
      # - MAIL_ENCRYPTION=tls
      # - MAIL_FROM_ADDRESS=your_email@gmail.com
    volumes:
      # DSM Docker에서는 Docker 볼륨을 사용하는 것이 더 안정적임
      - bookstack_config:/config
      # 선택: 추가 데이터 저장소
      - bookstack_uploads:/app/www/uploads
      - bookstack_storage:/app/www/storage
    networks:
      - bookstack-network
    # MariaDB 서비스 의존성 설정
    depends_on:
      bookstack_db:
        condition: service_healthy
    # 메모리 제한
    # mem_limit: 512m

  # MariaDB 데이터베이스
  bookstack_db:
    image: mariadb:11
    container_name: bookstack_db
    restart: on-failure:2
    # DSM Docker에서는 user 설정 제거 (권한 문제 해결)
    # user: "1026:100"
    environment:
      # 필수: 데이터베이스 설정 (BookStack과 일치)
      - MARIADB_ROOT_PASSWORD=JSlee.9500266
      - MARIADB_DATABASE=bookstackapp
      - MARIADB_USER=bookstack
      - MARIADB_PASSWORD=JSlee.9500266
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      # 권한 문제 해결을 위한 추가 설정
      - MARIADB_MYSQL_LOCALHOST_USER=1
      - MARIADB_MYSQL_LOCALHOST_GRANTS=USAGE
    volumes:
      - bookstack_database:/var/lib/mysql
    networks:
      - bookstack-network
    # 메모리 제한
    # mem_limit: 256m
    # 헬스체크 (MariaDB 11에서 권장되는 명령어 사용)
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  bookstack-network:
    driver: bridge

volumes:
  # Docker 볼륨 사용 (DSM과 호환성이 좋음)
  bookstack_config:
    driver: local
  bookstack_uploads:
    driver: local
  bookstack_storage:
    driver: local
  bookstack_database:
    driver: local
