version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mattermost-postgres
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: mattermost
      POSTGRES_PASSWORD: mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost-network
    restart: unless-stopped

  # Mattermost
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    ports:
      - "8081:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8081
      - MM_SERVICESETTINGS_ENABLEUSERCREATION=true
      - MM_SERVICESETTINGS_ENABLEOPENSERVER=true
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_config:/mattermost/config
    depends_on:
      - postgres
    networks:
      - mattermost-network
    restart: unless-stopped

volumes:
  postgres_data:
  mattermost_data:
  mattermost_logs:
  mattermost_config:

networks:
  mattermost-network:
    driver: bridge
