version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taiga-postgres
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taiga-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: taiga-redis
    networks:
      - taiga-network
    restart: unless-stopped

  # Taiga Backend
  taiga-back:
    image: taigaio/taiga-back:latest
    container_name: taiga-back
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
      - PUBLIC_REGISTER_ENABLED=true
      - DEFAULT_FROM_EMAIL=admin@yourcompany.com
      - SERVER_EMAIL=admin@yourcompany.com
    volumes:
      - taiga_media:/taiga-back/media
      - taiga_static:/taiga-back/static
    depends_on:
      - postgres
      - redis
    networks:
      - taiga-network
    restart: unless-stopped

  # Taiga Frontend
  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-front
    environment:
      - TAIGA_URL=http://localhost:8080
      - TAIGA_WEBSOCKETS_URL=ws://localhost:8080
    volumes:
      - taiga_static:/taiga-front/dist
    depends_on:
      - taiga-back
    networks:
      - taiga-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: taiga-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - taiga_static:/var/www/taiga:ro
    depends_on:
      - taiga-front
      - taiga-back
    networks:
      - taiga-network
    restart: unless-stopped

volumes:
  postgres_data:
  taiga_media:
  taiga_static:

networks:
  taiga-network:
    driver: bridge
